# Generated by Django 5.2.17 on 2026-10-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('started', 'Boshlangan'), ('needs_fix', 'Tuzatish kerak'), ('pending_approval', 'Tasdiqlash kutilmoqda'), ('done', 'Yakunlangan')], db_index=True, default='planned', max_length=16, verbose_name='Daraja'),
        ),
    ]
