# Generated by Django 5.2.17 on 2026-10-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_code_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Loyiha raqami'),
        ),
    ]
