# Generated by Django 5.2.17 on 2026-10-05 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Dasturchi tasdig'i so'ralgan payt"),
        ),
        migrations.CreateModel(
            name='ProjectCompletionAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=None, null=True, verbose_name='Tasdiqladi')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Rad etish sababi')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_acks', to='projects.project')),
            ],
            options={
                'verbose_name': "Loyiha yakunlash tasdig'i",
                'verbose_name_plural': 'Loyiha yakunlash tasdiqlari',
                'constraints': [models.UniqueConstraint(fields=('project', 'developer'), name='uniq_project_completion_ack')],
            },
        ),
    ]
