# Generated by Django 5.2.17 on 2026-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_note',
            field=models.TextField(blank=True, verbose_name='Yakunlash izohi'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_completion',
            field=models.BooleanField(default=False),
        ),
    ]
