# Generated by Django 5.2.17 on 2026-10-06 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_owner_status_date_idx'),
        ('projects', '0009_project_completion_note_projectfile_is_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['end_date', 'stage'], name='project_end_stage_idx'),
        ),
    ]
