# Generated by Django 5.2.17 on 2026-09-28 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_submitted', 'Yangi buyurtma'), ('order_approved', 'Buyurtma tasdiqlandi'), ('order_rejected', 'Buyurtma rad etildi'), ('order_resubmitted', 'Yangi TZ versiyasi'), ('task_assigned', 'Vazifa berildi'), ('task_submitted', 'Tekshiruvga yuborildi'), ('task_accepted', 'Vazifa qabul qilindi'), ('task_returned', 'Vazifa qaytarildi'), ('comment', 'Yangi izoh')], max_length=32)),
                ('message', models.CharField(max_length=255)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
