# Generated by Django 5.2.17 on 2026-10-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_submitted', 'Yangi buyurtma'), ('order_approved', 'Buyurtma tasdiqlandi'), ('order_rejected', 'Buyurtma rad etildi'), ('order_resubmitted', 'Yangi TZ versiyasi'), ('task_assigned', 'Vazifa berildi'), ('task_submitted', 'Tekshiruvga yuborildi'), ('task_accepted', 'Vazifa qabul qilindi'), ('task_returned', 'Vazifa qaytarildi'), ('comment', 'Yangi izoh'), ('project_completion_requested', "Loyihani yakunlashni tasdiqlash so'raldi"), ('project_completion_approved', 'Loyihani yakunlash tasdiqlandi'), ('project_completion_rejected', 'Loyihani yakunlash rad etildi')], max_length=32),
        ),
    ]
