# Generated by Django 5.2.17 on 2026-10-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_submitted', 'Yangi buyurtma'), ('order_approved', 'Buyurtma tasdiqlandi'), ('order_rejected', 'Buyurtma rad etildi'), ('order_resubmitted', 'Yangi TZ versiyasi'), ('task_assigned', 'Vazifa berildi'), ('task_submitted', 'Tekshiruvga yuborildi'), ('task_accepted', 'Vazifa qabul qilindi'), ('task_returned', 'Vazifa qaytarildi'), ('task_submit_ack_requested', "Tekshiruvga yuborishga tasdiq so'raldi"), ('task_submit_ack_rejected', 'Tekshiruvga yuborish rad etildi'), ('comment', 'Yangi izoh'), ('project_completion_ack_requested', "Loyihani yakunlashga tasdiq so'raldi"), ('project_completion_ack_rejected', 'Dasturchi yakunlashni rad etdi'), ('project_completion_ack_done', 'Barcha dasturchilar tasdiqladi'), ('project_completion_requested', "Loyihani yakunlashni tasdiqlash so'raldi"), ('project_completion_approved', 'Loyihani yakunlash tasdiqlandi'), ('project_completion_rejected', 'Loyihani yakunlash rad etildi')], max_length=32),
        ),
    ]
