# Generated by Django 5.2.17 on 2026-10-06 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0003_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.CharField(blank=True, max_length=32)),
                ('sent_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at', '-id'], name='notification_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramdelivery',
            index=models.Index(fields=['sent_at', 'failed_at', 'available_at'], name='telegram_pending_idx'),
        ),
    ]
