# Generated by Django 5.2.17 on 2026-09-28 05:31

import apps.core.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Qisqacha izoh')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rtacha"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=16, verbose_name='Muhimlik')),
                ('requested_due_date', models.DateField(verbose_name="Boshqarma so'ragan muddat")),
                ('status', models.CharField(choices=[('submitted', 'Yuborilgan'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('project_created', 'Loyiha yaratilgan')], db_index=True, default='submitted', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='PM belgilagan boshlanish')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='PM belgilagan tugash')),
                ('pm_note', models.TextField(blank=True, verbose_name='PM izohi')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_orders', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar (TZ)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Versiya')),
                ('file', models.FileField(upload_to=apps.core.files.UploadTo('orders/tz'), validators=[apps.core.files.validate_upload])),
                ('original_name', models.CharField(max_length=255, verbose_name='Asl fayl nomi')),
                ('note', models.TextField(blank=True, verbose_name='Nima tuzatildi')),
                ('decision', models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=16)),
                ('reject_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orders.order')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TZ versiyasi',
                'verbose_name_plural': 'TZ versiyalari',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('order', 'number'), name='uniq_order_version_number')],
            },
        ),
    ]
