# Generated by Django 5.2.17 on 2026-10-06 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['submitted_by', 'status', '-created_at'], name='order_owner_status_date_idx'),
        ),
    ]
