# Generated by Django 5.2.17 on 2026-10-08 08:34

import apps.core.files
import apps.portfolio.files
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_project_project_end_stage_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Tavsif')),
                ('link', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Havola')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'Portfolio loyihasi',
                'verbose_name_plural': 'Portfolio loyihalari',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Yulduz')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Sharh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_reviews', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='portfolio.portfolioitem')),
            ],
            options={
                'verbose_name': 'Baho va sharh',
                'verbose_name_plural': 'Baholar va sharhlar',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.core.files.UploadTo('portfolio/videos'), validators=[apps.portfolio.files.validate_video])),
                ('original_name', models.CharField(max_length=255, verbose_name='Asl fayl nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio videosi',
                'verbose_name_plural': 'Portfolio videolari',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kuzatuvchi',
                'verbose_name_plural': 'Kuzatuvchilar',
                'constraints': [models.UniqueConstraint(fields=('follower', 'developer'), name='uniq_follow'), models.CheckConstraint(condition=models.Q(('follower', models.F('developer')), _negated=True), name='follow_not_self')],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolioitem',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('owner', 'project'), name='uniq_portfolio_owner_project'),
        ),
        migrations.AddConstraint(
            model_name='portfolioreview',
            constraint=models.UniqueConstraint(fields=('item', 'author'), name='uniq_portfolio_review'),
        ),
        migrations.AddConstraint(
            model_name='portfolioreview',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='portfolio_review_stars_1_5'),
        ),
    ]
