# Generated by Django 5.2.17 on 2026-10-08 09:52

from django.db import migrations, models


def fill_sizes(apps, schema_editor):
    """Mavjud videolar hajmi diskdan olinadi (kvota hisobi to'g'ri bo'lsin). Fayl topilmasa — 0."""
    PortfolioVideo = apps.get_model("portfolio", "PortfolioVideo")
    for video in PortfolioVideo.objects.all().iterator():
        try:
            size = video.file.size
        except (OSError, ValueError):
            continue
        PortfolioVideo.objects.filter(pk=video.pk).update(size=size)


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliovideo',
            name='size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Hajmi'),
        ),
        migrations.RunPython(fill_sizes, migrations.RunPython.noop),
    ]
