# Generated by Django 5.2.17 on 2026-10-09 05:45

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_feed_indexes_and_backfill_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='cover',
            field=models.ImageField(blank=True, upload_to=apps.core.files.UploadTo('portfolio/covers'), verbose_name='Muqova rasmi'),
        ),
    ]
