# Generated by Django 5.2.17 on 2026-10-09 12:27

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_video_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to=apps.core.files.UploadTo('portfolio/previews'), verbose_name='Preview rasm'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_type',
            field=models.CharField(blank=True, choices=[('website', 'Veb-sayt'), ('mobile', 'Mobil ilova'), ('backend', 'Backend / API'), ('other', 'Boshqa')], max_length=20, verbose_name='Loyiha turi'),
        ),
    ]
