/**
 * Barcha interfeys matnlari — BITTA joyda (CLAUDE.md, 8-bo'lim).
 * Auditoriya 18–40 yosh: qisqa, oddiy, texnik atamasiz so'zlar.
 */
export const T = {
  app: "TeamFlow",
  common: {
    save: "Saqlash",
    cancel: "Bekor qilish",
    close: "Yopish",
    back: "Orqaga",
    next: "Keyingi",
    edit: "Tahrirlash",
    delete: "O'chirish",
    add: "Qo'shish",
    open: "Ochish",
    download: "Yuklab olish",
    search: "Qidirish",
    clear: "Tozalash",
    all: "Hammasi",
    loading: "Yuklanmoqda…",
    retry: "Qayta urinish",
    none: "—",
    notSet: "Belgilanmagan",
    confirmDelete: "Rostdan o'chirilsinmi? Bu amalni qaytarib bo'lmaydi.",
    yes: "Ha, o'chirish",
    unsaved: "Saqlanmagan o'zgarishlar bor. Baribir yopilsinmi?",
    errorGeneric: "Nimadir xato ketdi. Internetni tekshirib, qayta urinib ko'ring.",
    forbidden: "Bu amal uchun ruxsatingiz yo'q.",
    notFound: "Topilmadi yoki sizga ko'rinmaydi.",
    saved: "Saqlandi",
    files: "Fayllar",
    noFiles: "Fayl yo'q",
    attach: "Fayl biriktirish",
    attachHint: "Word, PDF yoki rasm · 20 MB gacha",
    comments: "Izohlar",
    required: "Majburiy maydon",
    daysLeft: (n: number) => (n === 0 ? "Bugun tugaydi" : `${n} kun qoldi`),
    daysLate: (n: number) => `${n} kun kechikdi`,
    count: (n: number) => `${n} ta`,
  },
  time: {
    now: "hozirgina",
    minutes: (n: number) => `${n} daqiqa oldin`,
    hours: (n: number) => `${n} soat oldin`,
    days: (n: number) => `${n} kun oldin`,
  },
  taskStatusHint: {
    control: "Vazifa berildi, hali boshlanmagan",
    in_progress: "Ustida ishlanmoqda",
    in_review: "Menejer tekshirmoqda",
    done: "Qabul qilindi",
  } as Record<string, string>,

  nav: {
    groupMain: "Asosiy ish",
    groupTeam: "Muloqot",
    groupControl: "Kuzatuv",
    dashboard: "Bosh panel",
    projects: "Loyihalar",
    orders: "Buyurtmalar (TZ)",
    myOrders: "Buyurtmalarim",
    tasks: "Vazifalar",
    myWork: "Mening ishim",
    calendar: "Taqvim",
    people: "Xodimlar",
    notifications: "Bildirishnomalar",
    review: "Tekshiruv navbati",
    history: "Umumiy tarix",
    logout: "Chiqish",
    menu: "Menyu",
    theme: "Tungi / kunduzgi rejim",
    searchPlaceholder: "Vazifa, loyiha yoki odamni qidiring",
  },

  auth: {
    loginTitle: "Tizimga kirish",
    loginSubtitle: "Jamoa ishini bir joyda kuzating",
    username: "Login",
    password: "Parol",
    login: "Kirish",
    noAccount: "Akkauntingiz yo'qmi?",
    register: "Ro'yxatdan o'tish",
    registerTitle: "Ro'yxatdan o'tish",
    registerSubtitle: "Ma'lumotlaringizni to'ldiring — administrator tasdiqlagach kirasiz",
    firstName: "Ism",
    lastName: "Familiya",
    specialty: "Mutaxassislik",
    specialtyPick: "Tanlang",
    role: "Rolingiz",
    departmentName: "Boshqarma nomi",
    departmentHint: "Masalan: Axborot texnologiyalari boshqarmasi",
    passwordHint: "Kamida 8 belgi, faqat raqamdan iborat bo'lmasin",
    haveAccount: "Akkauntingiz bormi?",
    registered: "Arizangiz yuborildi!",
    registeredText: "Administrator akkauntingizni tasdiqlagach, login va parolingiz bilan kira olasiz.",
    toLogin: "Kirish sahifasiga",
    roleHints: {
      pm: "Loyiha yaratadi, vazifa beradi, ishni tekshiradi",
      developer: "Vazifalarni bajaradi",
      department: "Buyurtma (TZ) yuboradi",
    } as Record<string, string>,
  },

  dashboard: {
    hello: (name: string) => `Salom, ${name}!`,
    managerSummary: (review: number, orders: number) =>
      review || orders
        ? `Sizni kutmoqda: ${review} ta tekshiruv, ${orders} ta yangi buyurtma.`
        : "Hozircha sizni kutayotgan ish yo'q.",
    devSummary: (active: number, overdue: number) =>
      active
        ? `Sizda ${active} ta faol vazifa${overdue ? `, ${overdue} tasining muddati o'tgan` : ""}.`
        : "Faol vazifangiz yo'q. Dam oling yoki menejeringizga yozing.",
    weeklyHeroTitle: "Haftalik jami ishlar",
    weeklyHeroSubtitle: (since: string) => `${since} dan bugungacha bo'lgan jami haftalik topshiriqlar`,
    weeklyTotal: (n: number) => `Jami: ${n} ta`,
    team: "Jamoa",
    teamHint: "Vazifasi yo'qlar birinchi turadi",
    everyone: "Hamma xodimlar",
    free: "Bo'sh",
    active: "Faol",
    overdue: "Muddati o'tgan",
    done: "Bajarilgan",
    late: "Kechikib bajarilgan",
    review: "Tekshiruv kutilmoqda",
    since: (d: string) => `${d} — bugun`,
    doingNow: "Hozir ustida ishlayapti",
    noDoing: "Hozir jarayonda vazifa yo'q",
    personTasks: "Vazifalari",
    tableTitle: (a: string, b: string) => `${a} — ${b}`,
    pickCard: "Ro'yxatni ko'rish uchun istalgan raqamni bosing",
    departmentTitle: "Buyurtmalaringiz holati",
  },

  filters: {
    search: "Qidiruv",
    searchPh: "Vazifa nomi",
    due: "Muddat",
    dueAll: "Hammasi",
    dueToday: "Bugun",
    dueWeek: "Shu hafta",
    dueMonth: "Shu oy",
    date: "Sana",
    half: "Oy yarmi",
    half1: "1–15",
    half2: "16–31",
    status: "Holat",
    project: "Loyiha",
    projectPh: "Loyiha nomi",
    person: "Xodim",
    personPh: "Xodim ismi",
    allProjects: "Barcha loyihalar",
  },

  tasks: {
    title: "Vazifalar",
    new: "Yangi vazifa",
    empty: "Vazifa topilmadi",
    emptyHint: "Filtrlarni tozalab ko'ring yoki yangi vazifa yarating.",
    col: { title: "Vazifa", status: "Holat", priority: "Muhimlik", assignees: "Ijrochilar", due: "Muddat" },
    project: "Loyiha",
    name: "Vazifa nomi",
    namePh: "Masalan: Kirish sahifasini yaratish",
    description: "Izoh",
    descriptionPh: "Nima qilish kerakligini qisqacha yozing",
    priority: "Muhimlik",
    startsAt: "Boshlanish vaqti",
    dueAt: "Tugash vaqti (muddat)",
    assignees: "Ijrochilar",
    assigneesHint: "Bir nechta dasturchini tanlash mumkin. Faqat loyiha jamoasi ko'rinadi.",
    noTeam: "Loyihada hali dasturchi yo'q. Avval loyihaga jamoa qo'shing.",
    pickProject: "Avval loyihani tanlang",
    subtasks: "Sub-vazifalar",
    subtaskPh: "Kichik qadam",
    subtaskAdd: "Sub-vazifa qo'shish",
    subtaskNobody: "Hamma",
    createdBy: "Vazifani bergan",
    tabMain: "Umumiy",
    tabReview: "Tekshiruv tarixi",
    start: "Boshlash",
    submit: "Tekshiruvga yuborish",
    submitTitle: "Nima qildingiz?",
    submitPh: "Qilgan ishingizni qisqacha yozing — menejer shuni ko'radi",
    submitSend: "Yuborish",
    accept: "Qabul qilish",
    return: "Qaytarish",
    returnTitle: "Nima tuzatilishi kerak?",
    returnPh: "Dasturchi nimani tuzatishini aniq yozing",
    returnSend: "Qaytarish",
    round: (n: number) => `${n}-urinish`,
    noSubmissions: "Hali tekshiruvga yuborilmagan",
    reviewer: "Tekshirdi",
    createdToast: "Vazifa yaratildi",
    startedToast: "Vazifa boshlandi",
    submittedToast: "Tekshiruvga yuborildi",
    acceptedToast: "Vazifa qabul qilindi",
    returnedToast: "Vazifa qaytarildi",
    deletedToast: "Vazifa o'chirildi",
  },

  board: {
    title: "Mening ishim",
    hint: "Kartani sichqoncha bilan keyingi ustunga sudrang",
    emptyCol: "Bu yerga karta sudrang",
    emptyDone: "Menejer qabul qilgan vazifalar shu yerda",
    locked: "Faqat menejer qabul qiladi",
    cantMove: "Vazifani bu ustunga o'tkazib bo'lmaydi",
    moveTo: "O'tkazish",
    actions: "Amallar",
  },

  review: {
    title: "Tekshiruv navbati",
    empty: "Tekshiruvni kutayotgan vazifa yo'q",
    emptyHint: "Dasturchi ishni yuborganda shu yerda paydo bo'ladi.",
    sentBy: "Yubordi",
    open: "Ko'rib chiqish",
  },

  orders: {
    title: "Buyurtmalar (TZ)",
    myTitle: "Buyurtmalarim",
    new: "Yangi buyurtma",
    empty: "Buyurtma yo'q",
    emptyDept: "Birinchi buyurtmangizni yuboring — TZ faylini biriktiring va muddatni belgilang.",
    emptyManager: "Boshqarmalar buyurtma yuborganda shu yerda ko'rinadi.",
    tabs: { submitted: "Yangi", approved: "Tasdiqlangan", rejected: "Rad etilgan", project_created: "Loyiha bo'lgan" } as Record<string, string>,
    name: "Buyurtma nomi",
    namePh: "Masalan: Hujjat aylanishi tizimi",
    description: "Qisqacha izoh",
    descriptionPh: "Nima kerakligini 2–3 gapda yozing",
    priority: "Muhimlik",
    dueDate: "Qachongacha kerak",
    tzFile: "TZ fayli",
    tzHint: "Word (.docx) yoki PDF",
    send: "Yuborish",
    sentToast: "Buyurtma yuborildi",
    department: "Boshqarma",
    sender: "Yuborgan",
    requestedDue: "So'ralgan muddat",
    pmDates: "Menejer belgilagan muddat",
    responsiblePm: "Mas'ul menejer",
    sentAt: "Yuborilgan",
    pmNote: "Menejer izohi",
    steps: ["Yuborildi", "Ko'rib chiqish", "Qaror", "Loyiha"],
    tabMain: "Umumiy",
    tabDoc: "TZ hujjat",
    tabHistory: "Versiyalar",
    version: (n: number) => `v${n}`,
    fixed: "Nima tuzatildi",
    rejectReason: "Rad etish sababi",
    approve: "Tasdiqlash",
    approveTitle: "Muddatni belgilang",
    startDate: "Boshlanish sanasi",
    endDate: "Tugash sanasi",
    note: "Qisqa izoh",
    notePh: "Boshqarmaga izoh (ixtiyoriy)",
    reject: "Rad etish",
    rejectTitle: "Nima uchun rad etilyapti?",
    rejectPh: "Boshqarma nimani tuzatishi kerakligini yozing",
    newVersion: "Yangi TZ yuborish",
    newVersionTitle: "Tuzatilgan TZ",
    newVersionPh: "Qaysi kamchiliklar tuzatildi?",
    waitingDecision: "TZ ko'rib chiqilmoqda. Qaror chiqquncha yangi versiya yuborib bo'lmaydi.",
    rejectedInfo: "Buyurtma rad etildi. Kamchiliklarni tuzatib, yangi TZ yuboring.",
    createProject: "Loyiha yaratish",
    openProject: "Loyihani ochish",
    editDates: "Sanani o'zgartirish",
    approvedToast: "Buyurtma tasdiqlandi",
    rejectedToast: "Buyurtma rad etildi",
    versionToast: "Yangi TZ yuborildi",
    datesToast: "Sanalar yangilandi",
  },

  projects: {
    title: "Loyihalar",
    new: "Yangi loyiha",
    empty: "Loyiha yo'q",
    emptyHint: "Loyiha yarating yoki tasdiqlangan buyurtmadan loyiha oching.",
    emptyDev: "Sizni hali loyihaga qo'shishmagan.",
    name: "Loyiha nomi",
    namePh: "Masalan: Ichki portal",
    description: "Izoh",
    stage: "Holati",
    startDate: "Boshlanish",
    endDate: "Tugash",
    team: "Jamoa",
    teamHint: "Loyihada ishlaydigan dasturchilarni belgilang",
    teamEmpty: "Hali dasturchi qo'shilmagan",
    progress: (d: number, t: number) => `${d} / ${t} vazifa bajarildi`,
    fromOrder: "Buyurtmadan",
    fromOrderLocked: "Buyurtmadan yaratilgan: nomi va izohi o'zgarmaydi, faqat sanalar.",
    steps: ["Asosiy", "Jamoa", "Vazifa va fayllar"],
    quickTasks: "Birinchi vazifalar (ixtiyoriy)",
    quickTaskPh: "Vazifa nomi",
    quickTaskAdd: "Vazifa qo'shish",
    create: "Loyihani yaratish",
    createdToast: "Loyiha yaratildi",
    tabMain: "Umumiy",
    tabTasks: "Vazifalar",
    tabTeam: "Jamoa",
    tabFiles: "Fayllar",
    addTask: "Vazifa qo'shish",
    saveTeam: "Jamoani saqlash",
    teamSaved: "Jamoa yangilandi",
    order: "Buyurtma",
    createdBy: "Yaratgan",
    endBeforeStart: "Tugash sanasi boshlanishdan oldin bo'lmasin",
    tzIncluded: (name: string) => `Buyurtma TZ fayli avtomatik qo'shiladi: ${name}`,
    tasksCount: (n: number) => `${n} ta dasturchi uchun`,
  },

  calendar: {
    title: "Taqvim",
    today: "Bugun",
    weekdays: ["Du", "Se", "Ch", "Pa", "Ju", "Sh", "Ya"],
    months: ["Yanvar", "Fevral", "Mart", "Aprel", "May", "Iyun", "Iyul", "Avgust", "Sentyabr", "Oktyabr", "Noyabr", "Dekabr"],
    more: (n: number) => `yana ${n} ta`,
    hint: "Vazifalar tugash sanasi bo'yicha",
  },

  notifications: {
    title: "Bildirishnomalar",
    readAll: "Hammasini o'qildi deb belgilash",
    empty: "Bildirishnoma yo'q",
    emptyHint: "Yangi vazifa, tekshiruv yoki buyurtma bo'lsa, shu yerda ko'rasiz.",
    unread: "O'qilmagan",
  },

  history: {
    title: "Umumiy tarix",
    empty: "Hali hech narsa bo'lmagan",
    searchPh: "Tarixdan qidirish",
  },

  comments: {
    empty: "Hali izoh yo'q. Birinchi bo'lib yozing.",
    placeholder: "Izoh yozing…",
    send: "Yuborish",
  },

  docs: {
    loading: "Hujjat ochilmoqda…",
    failed: "Hujjatni ko'rsatib bo'lmadi. Yuklab olib oching.",
    unsupported: "Bu turdagi faylni oldindan ko'rib bo'lmaydi. Yuklab oling.",
    zoomIn: "Kattalashtirish",
    zoomOut: "Kichraytirish",
    fullscreen: "To'liq ekran",
  },

  search: {
    title: "Qidiruv",
    placeholder: "Vazifa, loyiha, buyurtma yoki odam…",
    min: "Kamida 2 ta harf yozing",
    empty: "Hech narsa topilmadi",
    groups: { tasks: "Vazifalar", projects: "Loyihalar", orders: "Buyurtmalar", people: "Odamlar" } as Record<string, string>,
  },
} as const;
