/**
 * Barcha interfeys matnlari — BITTA joyda (CLAUDE.md, 8-bo'lim).
 * Auditoriya 18–40 yosh: qisqa, oddiy, texnik atamasiz so'zlar.
 */
export const T = {
  app: "TeamFlow",
  common: {
    save: "Saqlash",
    cancel: "Bekor qilish",
    close: "Yopish",
    back: "Orqaga",
    next: "Keyingi",
    edit: "Tahrirlash",
    delete: "O'chirish",
    add: "Qo'shish",
    open: "Ochish",
    download: "Yuklab olish",
    search: "Qidirish",
    pages: "Sahifalar",
    clear: "Tozalash",
    all: "Hammasi",
    loading: "Yuklanmoqda…",
    retry: "Qayta urinish",
    none: "—",
    notSet: "Belgilanmagan",
    confirmDelete: "Rostdan o'chirilsinmi? Bu amalni qaytarib bo'lmaydi.",
    yes: "Ha, o'chirish",
    unsaved: "Saqlanmagan o'zgarishlar bor. Baribir yopilsinmi?",
    errorGeneric: "Nimadir xato ketdi. Internetni tekshirib, qayta urinib ko'ring.",
    forbidden: "Bu amal uchun ruxsatingiz yo'q.",
    notFound: "Topilmadi yoki sizga ko'rinmaydi.",
    saved: "Saqlandi",
    files: "Fayllar",
    noFiles: "Fayl yo'q",
    attach: "Fayl biriktirish",
    attachHint: "Word, PDF yoki rasm · 20 MB gacha",
    dropBigTitle: "Faylni shu yerga tashlang",
    dropBigHint: "yoki tanlash uchun bosing",
    dropBigButton: "Fayl tanlash",
    attachedCount: (n: number) => `Biriktirilgan fayllar (${n})`,
    attachLimit: "20 MB gacha (Word, PDF yoki rasm)",
    fileRejected: (names: string, rule: string) => `Qabul qilinmadi: ${names}. Ruxsat: ${rule}.`,
    comments: "Izohlar",
    required: "Majburiy maydon",
    daysLeft: (n: number) => (n === 0 ? "Bugun tugaydi" : `${n} kun qoldi`),
    daysLate: (n: number) => `${n} kun kechikdi`,
    count: (n: number) => `${n} ta`,
  },
  time: {
    now: "hozirgina",
    minutes: (n: number) => `${n} daqiqa oldin`,
    hours: (n: number) => `${n} soat oldin`,
    days: (n: number) => `${n} kun oldin`,
  },
  taskStatusHint: {
    control: "Vazifa berildi, hali boshlanmagan",
    in_progress: "Ustida ishlanmoqda",
    in_review: "Menejer tekshirmoqda",
    done: "Qabul qilindi",
  } as Record<string, string>,

  nav: {
    groupMain: "Asosiy ish",
    groupTeam: "Muloqot",
    groupControl: "Kuzatuv",
    dashboard: "Bosh panel",
    projects: "Loyihalar",
    orders: "Buyurtmalar (TZ)",
    myOrders: "Buyurtmalarim",
    tasks: "Vazifalar",
    myWork: "Mening ishim",
    calendar: "Taqvim",
    people: "Xodimlar",
    notifications: "Bildirishnomalar",
    suggestions: "Takliflar",
    review: "Tekshiruv navbati",
    logout: "Chiqish",
    menu: "Menyu",
    theme: "Tungi / kunduzgi rejim",
    searchPlaceholder: "Vazifa, loyiha yoki odamni qidiring",
    profile: "Profil",
    workDone: "Qilingan ishlar",
    messages: "Xabarlar",
    portfolio: "Portfolio",
  },

  auth: {
    loginTitle: "Tizimga kirish",
    loginSubtitle: "Jamoa ishini bir joyda kuzating",
    username: "Login",
    password: "Parol",
    login: "Kirish",
    noAccount: "Akkauntingiz yo'qmi?",
    register: "Ro'yxatdan o'tish",
    registerTitle: "Ro'yxatdan o'tish",
    registerSubtitle: "Ma'lumotlaringizni to'ldiring — administrator tasdiqlagach kirasiz",
    firstName: "Ism",
    lastName: "Familiya",
    specialty: "Mutaxassislik",
    specialtyPick: "Tanlang",
    role: "Rolingiz",
    departmentName: "Boshqarma nomi",
    departmentHint: "Masalan: Axborot texnologiyalari boshqarmasi",
    passwordHint: "Kamida 8 belgi, faqat raqamdan iborat bo'lmasin",
    telegram: "Telegram (ixtiyoriy)",
    telegramHint: "Bildirishnomalar uchun, masalan: @username",
    telegramPh: "@username",
    haveAccount: "Akkauntingiz bormi?",
    registered: "Arizangiz yuborildi!",
    registeredText: "Administrator akkauntingizni tasdiqlagach, login va parolingiz bilan kira olasiz.",
    toLogin: "Kirish sahifasiga",
    roleHints: {
      pm: "Loyiha yaratadi, vazifa beradi, ishni tekshiradi",
      developer: "Vazifalarni bajaradi",
      department: "Buyurtma (TZ) yuboradi",
      user: "Dasturchilar portfoliosini ko'radi va baholaydi",
    } as Record<string, string>,
  },

  dashboard: {
    managerSummary: (review: number, orders: number) =>
      review || orders
        ? `Sizni kutmoqda: ${review} ta tekshiruv, ${orders} ta yangi buyurtma.`
        : "Hozircha sizni kutayotgan ish yo'q.",
    devSummary: (active: number, overdue: number) =>
      active
        ? `Sizda ${active} ta faol vazifa${overdue ? `, ${overdue} tasining muddati o'tgan` : ""}.`
        : "Faol vazifangiz yo'q. Dam oling yoki menejeringizga yozing.",
    weeklyHeroTitle: "Haftalik jami ishlar",
    weeklyHeroSubtitle: (since: string) => `${since} dan bugungacha bo'lgan jami haftalik topshiriqlar`,
    weeklyTotal: (n: number) => `Jami: ${n} ta`,
    weekActive: "Hafta boshidan — Faol",
    team: "Jamoa",
    everyone: "Hamma xodimlar",
    free: "Bo'sh",
    active: "Faol",
    overdue: "Muddati o'tgan",
    done: "Bajarilgan",
    late: "Kechikib bajarilgan",
    review: "Tekshiruv kutilmoqda",
    since: (d: string) => `${d} — bugun`,
    doingNow: "Hozir ustida ishlayapti",
    noDoing: "Hozir jarayonda vazifa yo'q",
    personTasks: "Vazifalari",
    tableTitle: (a: string, b: string) => `${a} — ${b}`,
    pickCard: "Ro'yxatni ko'rish uchun istalgan raqamni bosing",
    departmentTitle: "Buyurtmalaringiz holati",
    deptOrders: "Buyurtmalaringiz",
    deptSent: "Yuborilgan",
    deptRejected: "Rad etilgan",
    deptApproved: "Tasdiqlangan",
  },

  filters: {
    search: "Qidiruv",
    searchPh: "Vazifa nomi yoki kodi",
    due: "Muddat",
    dueAll: "Hammasi",
    dueToday: "Bugun",
    dueWeek: "Shu hafta",
    dueMonth: "Shu oy",
    date: "Sana",
    dateRange: "Sana (dan — gacha)",
    dateFrom: "Sanadan",
    dateTo: "Sanagacha",
    status: "Holat",
    project: "Loyiha",
    person: "Xodim",
    personPh: "Xodim ismi",
    allProjects: "Barcha loyihalar",
    toggle: "Filtrlar",
    clear: "Filtrni tozalash",
  },

  tasks: {
    new: "Yangi vazifa",
    empty: "Vazifa topilmadi",
    emptyHint: "Filtrlarni tozalab ko'ring yoki yangi vazifa yarating.",
    col: { title: "Vazifa", status: "Holat", priority: "Muhimlik", assignees: "Ijrochilar", due: "Muddat" },
    project: "Loyiha",
    name: "Vazifa nomi",
    namePh: "Masalan: Kirish sahifasini yaratish",
    description: "Izoh",
    descriptionPh: "Nima qilish kerakligini qisqacha yozing",
    priority: "Muhimlik",
    startsAt: "Boshlanish vaqti",
    dueAt: "Tugash vaqti (muddat)",
    assignees: "Ijrochilar",
    assigneesHint: "Bir nechta dasturchini tanlash mumkin. Faqat loyiha jamoasi ko'rinadi.",
    noTeam: "Loyihada hali dasturchi yo'q. Avval loyihaga jamoa qo'shing.",
    pickProject: "Avval loyihani tanlang",
    subtasks: "Topshiriqlar",
    subtaskPh: "Kichik qadam",
    subtaskAdd: "Topshiriq qo'shish",
    subtaskNobody: "Hamma",
    createdBy: "Vazifani bergan",
    tabMain: "Umumiy",
    tabReview: "Tekshiruv tarixi",
    start: "Boshlash",
    submit: "Tekshiruvga yuborish",
    submitSubtitle: "Bajarilgan ishni tekshiruv uchun yuboring.",
    submitTitle: "Nima qildingiz?",
    submitPh: "Qilgan ishingizni qisqacha yozing — menejer shuni ko'radi",
    submitCounter: (n: number, max: number) => `${n}/${max}`,
    accept: "Qabul qilish",
    return: "Qaytarish",
    returnSubtitle: "Dasturchiga nima tuzatish kerakligini tushuntiring.",
    returnTitle: "Nima tuzatilishi kerak?",
    returnPh: "Dasturchi nimani tuzatishini aniq yozing",
    returnSend: "Qaytarish",
    round: (n: number) => `${n}-urinish`,
    noSubmissions: "Hali tekshiruvga yuborilmagan",
    reviewer: "Tekshirdi",
    createdToast: "Vazifa yaratildi",
    startedToast: "Vazifa boshlandi",
    submittedToast: "Tekshiruvga yuborildi",
    acceptedToast: "Vazifa qabul qilindi",
    returnedToast: "Vazifa qaytarildi",
    deletedToast: "Vazifa arxivlandi",
    archiveConfirm: "Vazifa ro'yxatdan olinadi. Ish tarixi va fayllari saqlanadi.",
    archived: "Arxivlangan",
    info: "Ma'lumotlar",
    createdByShort: "Yaratdi",
    noFiles: "Fayllar yo'q",
    worklog: (hours: number) => `Ish jurnali (${hours} soat)`,
    worklogHours: "Sarflangan soat",
    worklogPh: "Bugun nima qildingiz?",
    worklogSave: "Qayd etish",
    worklogEmpty: "Hali ish qayd etilmagan. Qilgan ishingizni va sarflangan vaqtni yozib boring.",
    worklogItem: (hours: number) => `${hours} soat`,
    worklogSavedToast: "Ish jurnali saqlandi",
    subtaskAddedToast: "Topshiriq qo'shildi",
    subtaskDeletedToast: "Topshiriq o'chirildi",
    subtaskNewPh: "Nima qilinishi kerak?",
    subtaskPickPerson: "Kimga (ixtiyoriy)",
    subtaskPeople: "Ijrochilar",
    subtaskPeopleSavedToast: "Topshiriq ijrochilari saqlandi",
    picker: {
      searchPh: "Dasturchi ismini yozing",
      add: "Qo'shish",
      remove: (name: string) => `${name}ni olib tashlash`,
      noMatch: "Bunday dasturchi topilmadi",
      joinHint: "Jamoada bo'lmagan dasturchi tanlansa, u loyiha jamoasiga ham qo'shiladi.",
    },
    assigneesEdit: "O'zgartirish",
    assigneesSavedToast: "Ijrochilar saqlandi",
    upload: "Yuklash",
    bulkNew: "Ko'p vazifa qo'shish",
    bulkTitle: "Vazifalarni taqsimlash",
    bulkSubtitle: "Har bir vazifaga ijrochi tanlang",
    bulkMore: "Yana vazifa",
    notInTeam: "Tanlangan xodim bu loyiha jamoasida emas.",
    addToTeam: "Jamoaga qo'shish",
    addedToTeamToast: "Xodim loyiha jamoasiga qo'shildi",
  },

  board: {
    dragTask: "Vazifani sudrab o'tkazish",
    emptyCol: "Bu yerga karta sudrang",
    emptyDone: "Menejer qabul qilgan vazifalar shu yerda",
    locked: "Faqat menejer qabul qiladi",
    cantMove: "Vazifani bu ustunga o'tkazib bo'lmaydi",
    moveTo: "O'tkazish",
    actions: "Amallar",
  },

  review: {
    empty: "Tekshiruvni kutayotgan vazifa yo'q",
    emptyHint: "Dasturchi ishni yuborganda shu yerda paydo bo'ladi.",
    sentBy: "Yubordi",
    open: "Ko'rib chiqish",
  },

  orders: {
    new: "Yangi buyurtma",
    empty: "Buyurtma yo'q",
    emptyDept: "Birinchi buyurtmangizni yuboring — TZ faylini biriktiring va muddatni belgilang.",
    emptyManager: "Boshqarmalar buyurtma yuborganda shu yerda ko'rinadi.",
    tabs: { submitted: "Yangi", approved: "Tasdiqlangan", rejected: "Rad etilgan" } as Record<string, string>,
    name: "Buyurtma nomi",
    namePh: "Masalan: Hujjat aylanishi tizimi",
    description: "Qisqacha izoh",
    descriptionPh: "Nima kerakligini 2–3 gapda yozing",
    priority: "Muhimlik",
    dueDate: "Qachongacha kerak",
    tzFile: "TZ fayli",
    tzHint: "Word (.docx) yoki PDF",
    send: "Yuborish",
    sentToast: "Buyurtma yuborildi",
    department: "Boshqarma",
    sender: "Yuborgan",
    requestedDue: "So'ralgan muddat",
    pmDates: "Menejer belgilagan muddat",
    responsiblePm: "Mas'ul menejer",
    sentAt: "Yuborilgan",
    pmNote: "Menejer izohi",
    steps: ["Yuborildi", "Ko'rib chiqish", "Qaror", "Loyiha"],
    tabMain: "Umumiy",
    tabDoc: "TZ hujjat",
    tabHistory: "Versiyalar",
    version: (n: number) => `v${n}`,
    fixed: "Nima tuzatildi",
    rejectReason: "Rad etish sababi",
    approve: "Tasdiqlash",
    approveTitle: "Muddatni belgilang",
    approveSubtitle: "Buyurtmani tasdiqlang va loyiha muddatini belgilang.",
    rejectSubtitle: "Boshqarma kamchilikni tuzatib, yangi TZ yuboradi.",
    datesSubtitle: "Loyihaning boshlanish va tugash sanasini o'zgartiring.",
    newVersionSubtitle: "Kamchiliklarni tuzatgan TZ faylini yuboring.",
    rejectCompletionSubtitle: "Loyiha menejeri kamchilikni tuzatib, qayta so'raydi.",
    startDate: "Boshlanish sanasi",
    endDate: "Tugash sanasi",
    note: "Qisqa izoh",
    notePh: "Boshqarmaga izoh (ixtiyoriy)",
    reject: "Rad etish",
    rejectTitle: "Nima uchun rad etilyapti?",
    rejectPh: "Boshqarma nimani tuzatishi kerakligini yozing",
    newVersion: "Yangi TZ yuborish",
    newVersionTitle: "Tuzatilgan TZ",
    newVersionPh: "Qaysi kamchiliklar tuzatildi?",
    waitingDecision: "TZ ko'rib chiqilmoqda. Qaror chiqquncha yangi versiya yuborib bo'lmaydi.",
    rejectedInfo: "Buyurtma rad etildi. Kamchiliklarni tuzatib, yangi TZ yuboring.",
    createProject: "Loyiha yaratish",
    openProject: "Loyihani ochish",
    editDates: "Sanani o'zgartirish",
    approvedToast: "Buyurtma tasdiqlandi",
    rejectedToast: "Buyurtma rad etildi",
    versionToast: "Yangi TZ yuborildi",
    datesToast: "Sanalar yangilandi",
    completionTitle: "Loyiha yakunlandi deb belgilandi",
    confirmCompletion: "Yakunlashni tasdiqlash",
    rejectCompletion: "Kamchilik bor",
    rejectCompletionTitle: "Nima kamchilik bor?",
    rejectCompletionPh: "Loyiha menejeri nimani tuzatishi kerakligini yozing",
    completionConfirmedToast: "Loyiha yakunlanishi tasdiqlandi",
    completionRejectedToast: "Loyiha yakunlanishi rad etildi",
  },

  projects: {
    new: "Yangi loyiha",
    empty: "Loyiha yo'q",
    emptyHint: "Loyiha yarating yoki tasdiqlangan buyurtmadan loyiha oching.",
    emptyDev: "Sizni hali loyihaga qo'shishmagan.",
    code: "Loyiha raqami",
    codePh: "Masalan: PRJ-12",
    codeHint: "Boshqa loyihada ishlatilmagan bo'lishi kerak.",
    name: "Loyiha nomi",
    namePh: "Masalan: Ichki portal",
    description: "Izoh",
    stage: "Holati",
    startDate: "Boshlanish",
    endDate: "Tugash",
    team: "Jamoa",
    teamHint: "Loyihada ishlaydigan dasturchilarni belgilang",
    teamEmpty: "Hali dasturchi qo'shilmagan",
    progress: (d: number, t: number) => `${d} / ${t} vazifa bajarildi`,
    fromOrder: "Buyurtmadan",
    fromOrderLocked: "Buyurtmadan yaratilgan: bu yerdagi o'zgarish bog'liq buyurtmaga ham ko'chadi.",
    pendingApproval: "Loyiha yakunlandi deb belgilandi — endi buyurtma beruvchi boshqarma tasdiqlashini kutmoqda.",
    requestCompletion: "Yakunlash",
    completionModalTitle: "Loyihani yakunlash",
    completionModalSubtitle: "Bajarilgan ish haqida izoh yozing va kerakli fayllarni biriktiring.",
    completionNote: "Yakunlash izohi",
    completionNotePh: "Loyihada bajarilgan ishlar va natijani qisqacha yozing",
    completionSend: "Yuborish",
    completionReport: "Yakunlash hisoboti",
    requestCompletionToast: "Boshqarmaga yuborildi, tasdiqlashini kuting",
    completionAckToast: "Dasturchilarga so'rov yuborildi, javobini kutamiz",
    completionAckPending: (names: string) => `Yakunlashdan oldin dasturchi tasdig'i kutilmoqda: ${names}`,
    completionAckConfirmed: (names: string) => `Tasdiqladi: ${names}`,
    completionAckReady: "Barcha dasturchilar rozi. Endi loyihani yakunlashingiz mumkin.",
    completionAckWaitingPm: "Barcha dasturchilar rozi. PM loyiha yakunlanishini tasdiqlashi kutilmoqda.",
    steps: ["Asosiy", "Jamoa", "Vazifa va fayllar"],
    projectFiles: "Loyiha fayllari",
    memberTasks: "Xodimlarga vazifalar (ixtiyoriy)",
    memberTasksHint: "Har bir xodimga alohida vazifa bering: nomi, boshlanish va tugash vaqti, kerak bo'lsa fayl.",
    memberNoTasks: "Hali vazifa berilmagan",
    quickTaskPh: "Vazifa nomi",
    quickTaskAdd: "Vazifa qo'shish",
    taskFiles: "Vazifaga fayl biriktirish",
    taskEndBeforeStart: "Tugash vaqti boshlanishdan oldin bo'lmasin",
    create: "Loyihani yaratish",
    createdToast: "Loyiha yaratildi",
    tabMain: "Umumiy",
    tabTasks: "Vazifalar",
    tabTeam: "Jamoa",
    tabFiles: "Fayllar",
    addTask: "Vazifa qo'shish",
    saveTeam: "Jamoani saqlash",
    teamSaved: "Jamoa yangilandi",
    teamSearchPh: "Dasturchini qidiring va qo'shing",
    teamAdd: "Qo'shish",
    teamRemove: "Olib tashlash",
    teamNoMatch: "Bunday dasturchi topilmadi",
    teamUnsaved: "Saqlanmagan",
    teamSaveFirst: "Vazifa berishdan oldin jamoani saqlang.",
    giveTask: "Vazifa berish",
    order: "Buyurtma",
    createdBy: "Yaratgan",
    endBeforeStart: "Tugash sanasi boshlanishdan oldin bo'lmasin",
    tzIncluded: (name: string) => `Buyurtma TZ fayli avtomatik qo'shiladi: ${name}`,
    noActivity: "Hali faoliyat yo'q.",
    tabHistory: "Tarix",
    activityTitle: "Loyiha faolligi",
  },

  calendar: {
    previousMonth: "Oldingi oy",
    nextMonth: "Keyingi oy",
    title: "Taqvim",
    today: "Bugun",
    weekdays: ["Du", "Se", "Ch", "Pa", "Ju", "Sh", "Ya"],
    months: ["Yanvar", "Fevral", "Mart", "Aprel", "May", "Iyun", "Iyul", "Avgust", "Sentyabr", "Oktyabr", "Noyabr", "Dekabr"],
    more: (n: number) => `yana ${n} ta`,
    openDay: (date: string) => `${date} — kun ro'yxatini ochish`,
    projectEnds: (name: string) => `${name} — loyiha tugaydi`,
    dayProjects: "Shu kuni tugaydigan loyihalar",
    dayTasks: "Shu kungi vazifalar",
    dayCount: (tasks: number, projects: number) =>
      [tasks && `${tasks} ta vazifa`, projects && `${projects} ta loyiha`].filter(Boolean).join(" · ") || "Hech narsa yo'q",
    dayEmpty: "Bu kunga vazifa ham, loyiha muddati ham yo'q",
    dayEmptyHint: "Boshqa kunni tanlang yoki taqvimni oylar bo'yicha aylantiring.",
  },

  notifications: {
    title: "Bildirishnomalar",
    readAll: "Hammasini o'qildi deb belgilash",
    empty: "Bildirishnoma yo'q",
    emptyHint: "Yangi vazifa, tekshiruv yoki buyurtma bo'lsa, shu yerda ko'rasiz.",
    unread: "O'qilmagan",
    unreadCount: (n: number) => `${n} ta o'qilmagan bildirishnoma`,
    allRead: "Hammasi o'qilgan",
    emptyUnread: "O'qilmagan bildirishnoma yo'q",
    emptyUnreadHint: "Hammasini ko'rib chiqdingiz. Yangisi kelsa, shu yerda paydo bo'ladi.",
    today: "Bugun",
    yesterday: "Kecha",
    ackQuestion: "Loyihani yakunlashga rozimisiz?",
    ackConfirm: "Ha, roziman",
    ackReject: "Yo'q",
    ackReasonPh: "Sababini yozing…",
    ackReasonSend: "Yuborish",
    ackReasonRequired: "Sababini yozing",
    ackSent: "Javobingiz yuborildi",
  },

  comments: {
    empty: "Hali izoh yo'q. Birinchi bo'lib yozing.",
    placeholder: "Izoh yozing…",
    send: "Yuborish",
  },

  docs: {
    loading: "Hujjat ochilmoqda…",
    failed: "Hujjatni ko'rsatib bo'lmadi. Yuklab olib oching.",
    unsupported: "Bu turdagi faylni oldindan ko'rib bo'lmaydi. Yuklab oling.",
    zoomIn: "Kattalashtirish",
    zoomOut: "Kichraytirish",
    fullscreen: "To'liq ekran",
  },

  search: {
    title: "Qidiruv",
    placeholder: "Vazifa, loyiha, odam, vazifa kodi yoki loyiha raqami…",
    min: "Kamida 2 ta harf yozing",
    empty: "Hech narsa topilmadi",
    groups: { tasks: "Vazifalar", projects: "Loyihalar", orders: "Buyurtmalar", people: "Odamlar" } as Record<string, string>,
  },

  profile: {
    title: "Profil",
    businessTrips: "Xizmat safarlari",
    businessTripHint: "Boshliq xodimning qaytish sanasini belgilaydi. Shu sanagacha unga yangi vazifa berilmaydi.",
    tripEmployee: "Xodim",
    tripReturnDate: "Qaytish sanasi",
    tripSet: "Xizmat safariga chiqarish",
    tripEnd: "Safarni muddatidan oldin tugatish",
    tripSaved: "Xizmat safari saqlandi",
    tripEnded: "Xizmat safari tugatildi",
    photoUpload: "Rasm yuklash",
    photoChange: "Rasmni almashtirish",
    photoRemove: "Rasmni o'chirish",
    photoHint: "JPG, PNG yoki WEBP, 5 MB gacha",
    photoSavedToast: "Rasm saqlandi",
    photoRemovedToast: "Rasm o'chirildi",
    passwordTitle: "Parolni almashtirish",
    currentPassword: "Joriy parol",
    newPassword: "Yangi parol",
    changePassword: "Parolni almashtirish",
    passwordChangedToast: "Parol muvaffaqiyatli o'zgartirildi",
    editInfoTitle: "Ma'lumotlarni tahrirlash",
    firstName: "Ism",
    lastName: "Familiya",
    dateJoined: "Tizimga qo'shilgan vaqt",
    telegram: "Telegram",
    telegramHint: "Bildirishnomalar Telegram'ga ham kelsin desangiz: username yozing va botga /start yuboring.",
    /** Bot havolasi bilan: "…username yozing, saqlang va [@bot] ga /start yuboring." */
    telegramHintBefore: "Bildirishnomalar Telegram'ga ham kelsin desangiz: username yozing, saqlang va",
    telegramHintAfter: "botiga /start yuboring.",
    telegramPh: "@username",
    login: "Login",
    stats: "Vazifalaringiz",
    myTasks: "Mening vazifalarim",
    myTasksEmpty: "Sizga hali vazifa berilmagan. Menejer vazifa berganda shu yerda ko'rasiz.",
    savedToast: "Ma'lumotlar saqlandi",
  },

  people: {
    responsibilities: "Mas'uliyatlar",
    responsibilitiesHint: "Xodim qaysi ishlar va yo'nalishlarga mas'ul ekanini yozing.",
    responsibilitiesPlaceholder: "Masalan: backend API, serverlar va ma'lumotlar bazasiga mas'ul.",
    responsibilitiesEmpty: "Mas'uliyatlar hali kiritilmagan",
    responsibilitiesAdd: "Mas'uliyat kiritish",
    responsibilitiesEdit: "Mas'uliyatlarni tahrirlash",
    responsibilitiesSaved: "Mas'uliyatlar saqlandi",
    profileOpen: "Profilni ko'rish",
    workTitle: "Biriktirilgan ishlar",
    projectsTitle: "Biriktirilgan loyihalar",
    noWork: "Faol ish biriktirilmagan",
    noProjects: "Loyiha biriktirilmagan",
    moreWork: (n: number) => `Yana ${n} ta ish — profilda`,
    moreProjects: (n: number) => `Yana ${n} ta loyiha — profilda`,
    found: (n: number) => `${n} ta xodim`,
    onBusinessTrip: "Xizmat safarida",
    tripUntil: (date: string) => `Qaytish sanasi: ${date}`,
    tripBlocked: "Xizmat safaridan qaytguncha yangi vazifa berib bo'lmaydi",
    photoOpen: "Rasmni kattalashtirish",
    photoOf: (name: string) => `${name} — profil rasmi`,
    profileTitle: "Xodim profili",
    tabOverview: "Umumiy",
    tabProjects: "Loyihalar",
    portfolioOpen: "Portfolio",
    noTasksHint: "Bu xodimga hali vazifa berilmagan. \"Vazifa berish\" tugmasi orqali bering.",
    onlyFree: "Bo'sh xodimlar",
    viewTable: "Jadval",
    viewGrid: "Kartalar",
    searchPh: "Xodimni qidirish…",
    empty: "Xodimlar topilmadi",
    emptyHint: "Qidiruv yoki filtrni o'zgartirib ko'ring.",
    col: { person: "Xodim", position: "Lavozim / Bo'lim", load: "Bandlik", tasks: "Vazifalar", doing: "Biriktirilgan ishlar", actions: "Amallar" },
    activeN: (n: number) => `${n} faol`,
    overdueN: (n: number) => `${n} kechikkan`,
    reviewN: (n: number) => `${n} tekshiruvda`,
    doneN: (n: number) => `${n} bajarilgan`,
    noTasks: "Vazifa yo'q",
    giveTask: "Vazifa berish",
    freeNow: "Hozir bo'sh — vazifasi yo'q",
    busyNow: (n: number) => `Band: ${n} ta faol vazifa`,
    freeHint: "Xodimga yangi vazifa bering",
    busyHint: "Yana vazifa berish mumkin",
    tasks: "Vazifalar",
    report: "Hisobot",
    donePercent: "Bajarilish foizi",
    onTimeRate: "O'z vaqtida bajarganlar ulushi",
    total: "Jami vazifalar:",
    doneTotal: "Bajarilgan:",
    doneLate: "Kechikib bajarilgan:",
    lateNow: "Hozir kechikkan:",
    reportNote: "Hisobot barcha vazifalar asosida. \"O'z vaqtida\" — bajarilganlardan qanchasi muddatidan oldin yopilgani.",
    devOnly: "Batafsil hisobot faqat dasturchilar uchun.",
  },

  chat: {
    searchPh: "Ism bo'yicha qidirish",
    notFound: "Hech kim topilmadi",
    noConversations: "Hali suhbat yo'q",
    noConversationsHint: "Yuqoridagi qidiruvdan hamkasbingizni toping va yozing.",
    pickTitle: "Suhbatni tanlang",
    pickHint: "Chapdagi ro'yxatdan suhbatni oching yoki qidiruv orqali yangi odamga yozing.",
    firstMessage: "Hali xabar yo'q. Birinchi bo'lib yozing!",
    messagePh: "Xabar yozing…",
    send: "Yuborish",
  },

  workDone: {
    tabs: { tasks: "Vazifalar", reviews: "Tekshiruvlar", history: "Tarix" } as Record<string, string>,
    mine: "Faqat men",
    days: "Kun",
    noTasks: "Yaqin orada bajarilgan vazifalar yo'q.",
    noReviews: "Yaqin orada tekshiruvlar yo'q.",
    noHistory: "Yaqin orada tarix yo'q.",
    decision: "Qaror",
    col: {
      task: "Vazifa", project: "Loyiha", assignees: "Ijrochilar", doneAt: "Bajarildi",
      submittedBy: "Yubordi", note: "Izoh", reviewer: "Tekshirdi", date: "Sana",
      person: "Xodim", action: "Nima qildi", time: "Vaqt",
    },
    prev: "← Oldingi",
    next: "Keyingi →",
    page: (n: number) => `${n}-sahifa`,
  },

  suggestions: {
    title: "Takliflar",
    new: "Yangi taklif",
    empty: "Takliflar yo'q",
    emptyHint: "O'z taklifingizni yozib qoldiring.",
    name: "Sarlavha",
    namePh: "Qisqacha nima haqida",
    body: "Taklif matni",
    bodyPh: "Batafsil tushuntirib bering",
    anonymous: "Anonim yuborish (ismingiz ko'rinmaydi)",
    author: "Muallif",
    anonymousAuthor: "Anonim",
    status: "Holat",
    tabs: { pending: "Ko'rib chiqilmoqda", accepted: "Qabul qilingan", rejected: "Rad etilgan" } as Record<string, string>,
    votes: "Ovozlar",
    voteFor: "Yoqlayman",
    voteAgainst: "Qarshiman",
    removeVote: "Ovozni bekor qilish",
    bossDecision: "Boshliq qarori",
    bossNote: "Boshliq izohi",
    accept: "Qabul qilish",
    reject: "Rad etish",
    sentToast: "Taklif yuborildi",
    votedToast: "Ovoz berildi",
    decidedToast: "Qaror qabul qilindi",
    deletedToast: "Taklif o'chirildi",
    send: "Yuborish",
    voteCounts: (forN: number, againstN: number) => `${forN} yoqlaydi · ${againstN} qarshi`,
    bossNotePh: "Qaroringiz sababini qisqacha yozing (ixtiyoriy)",
  },
  portfolio: {
    title: "Portfolio",
    mine: "Mening portfoliom",
    searchPh: "Ism, mutaxassislik yoki texnologiya bo'yicha qidirish…",
    found: (n: number) => `${n} ta dasturchi`,
    empty: "Dasturchilar topilmadi",
    emptyHint: "Qidiruvni o'zgartirib ko'ring.",
    developer: "Dasturchi",
    rank: (n: number) => `${n}-o'rin`,
    noRating: "Hali baholanmagan",
    starsOf: (value: number) => `5 dan ${value.toFixed(1)} yulduz`,
    reviewsN: (n: number) => `${n} ta sharh`,
    followersN: (n: number) => `${n} kuzatuvchi`,
    projectsN: (n: number) => `${n} loyiha`,
    tasksN: (n: number) => `${n} vazifa`,
    following: "Kuzatyapsiz",
    follow: "Kuzatish",
    unfollow: "Kuzatishni to'xtatish",
    followedToast: "Endi kuzatyapsiz",
    unfollowedToast: "Kuzatish to'xtatildi",
    viewProfile: "Profilni ko'rish",
    sort: "Saralash",
    sortRating: "Reyting bo'yicha",
    sortName: "Ism bo'yicha",
    summary: {
      developers: "Jami dasturchilar",
      avgRating: "O'rtacha reyting",
      ratedItems: "Baholangan loyihalar",
    },
    technologies: "Texnologiyalar",
    technologiesEdit: "Texnologiyalarni tahrirlash",
    technologiesPh: "Vergul bilan ajrating: React, Django, PostgreSQL",
    technologiesSaved: "Texnologiyalar saqlandi",
    projectType: "Loyiha turi",
    projectTypePick: "Tanlanmagan",
    previewImage: "Preview rasm",
    previewImagePick: "Rasm tanlash",
    previewImageHint: "JPG, PNG yoki WEBP · 8 MB gacha",
    previewImageUploaded: "Rasm yuklandi",
    previewImageDeleted: "Rasm o'chirildi",
    projectsTitle: "Loyihalar",
    projectsSearchPh: "Loyiha yoki dasturchi bo'yicha qidirish…",
    projectsFound: (n: number) => `${n} ta loyiha`,
    projectsGridEmpty: "Loyiha topilmadi",
    monthsTitle: "Oylar bo'yicha",
    weeksTitle: "Haftalar bo'yicha",
    tasksLate: "Kechikib bajarilgan",
    stat: {
      rating: "Reyting",
      followers: "Kuzatuvchilar",
      projects: "Loyihalar",
      tasks: "Bajarilgan vazifalar",
      experience: "Tajriba",
    },
    experience: (months: number) => {
      const y = Math.floor(months / 12);
      const m = months % 12;
      if (!y && !m) return "1 oydan kam";
      return [y ? `${y} yil` : "", m ? `${m} oy` : ""].filter(Boolean).join(" ");
    },
    since: (date: string) => `${date} dan beri`,
    projects: "Loyihalar",
    projectsEmpty: "Hali loyiha yo'q",
    projectsEmptyOwner: "TeamFlow'dagi loyihalaringiz shu yerda o'zi paydo bo'ladi. Boshqa joyda qilgan ishingizni \"Loyiha qo'shish\" bilan qo'shing.",
    projectsEmptyOther: "Bu dasturchi hali loyiha qo'shmagan.",
    years: "Yillar bo'yicha",
    yearRow: (projects: number, tasks: number) => `${projects} loyiha · ${tasks} bajarilgan vazifa`,
    recentTasks: "So'nggi bajarilgan vazifalar",
    auto: "TeamFlow loyihasi",
    manual: "O'zi qo'shgan",
    period: (from: string, to: string) => `${from} — ${to}`,
    now: "hozir",
    videosN: (n: number) => `${n} video`,
    add: "Loyiha qo'shish",
    addTitle: "Yangi loyiha",
    editTitle: "Loyihani tahrirlash",
    backToPortfolio: "Portfolioga qaytish",
    fields: {
      title: "Loyiha nomi",
      titlePh: "Masalan: Onlayn do'kon",
      description: "Nima qildingiz?",
      descriptionPh: "Loyiha haqida va undagi o'z ishingiz haqida qisqacha yozing",
      link: "Loyiha havolasi",
      linkPh: "https://…",
      linkHint: "Sayt, GitHub yoki do'kondagi sahifa",
      start: "Boshlanish",
      end: "Tugash",
      autoNote: "Nomi va sanalari TeamFlow loyihasidan olinadi.",
    },
    savedToast: "Loyiha saqlandi",
    deletedToast: "Loyiha o'chirildi",
    deleteItem: "Loyihani o'chirish",
    openLink: "Loyihani ochish",
    description: "Tavsif",
    videos: "Videolar",
    videosEmpty: "Video yo'q",
    videoPick: "Video tanlash",
    videoHint: "MP4, WebM yoki MOV · 100 MB gacha · 5 tagacha · jami 1 GB",
    videoUpload: "Videoni yuklash",
    videoUploadedToast: "Video yuklandi",
    videoDeletedToast: "Video o'chirildi",
    videoDelete: "Videoni o'chirish",
    videoUnsupported: "Brauzeringiz bu videoni ko'rsata olmaydi. Yuklab olib ko'ring.",
    reviews: "Baholar va sharhlar",
    reviewsEmpty: "Hali sharh yo'q",
    reviewsEmptyHint: "Birinchi bo'lib baho qo'ying.",
    myReview: "Sizning bahoyingiz",
    yourStars: "Baholash",
    starN: (n: number) => `${n} yulduz`,
    starLabels: ["", "Yomon", "O'rtacha emas", "O'rtacha", "Yaxshi", "A'lo"] as readonly string[],
    reviewText: "Sharh",
    reviewPh: "Loyiha haqida fikringizni yozing (ixtiyoriy)",
    reviewSave: "Bahoni saqlash",
    reviewUpdate: "Bahoni yangilash",
    reviewDelete: "Bahoni o'chirish",
    reviewSavedToast: "Bahoyingiz saqlandi",
    reviewDeletedToast: "Bahoyingiz o'chirildi",
    starsRequired: "Yulduzlardan birini tanlang",
    ownHint: "O'z loyihangizni baholay olmaysiz — boshqalar baholaydi.",
    chars: (n: number, max: number) => `${n}/${max}`,
  },
  landing: {
    title: "Jamoangiz bir joyda ishlaydigan platforma",
    subtitle: "Loyiha oching, jamoani mutaxassisligi bo'yicha yig'ing, vazifalarni bering va hammasini bitta tizimda kuzatib boring.",
    register: "Ro'yxatdan o'tish",
    login: "Kirish",
    features: [
      { key: "board", title: "Vazifalar doskasi", desc: "Vazifani ustunlar bo'ylab sudrab o'tkazing — kim nima qilayotgani darrov ko'rinadi." },
      { key: "orders", title: "Boshqarmalar bilan ishlash", desc: "Buyurtmalarni qabul qiling va ularni loyihaga aylantiring." },
      { key: "review", title: "Ishni tekshirish", desc: "Bajarilgan vazifa menejerga tekshiruvga tushadi, u qabul qiladi yoki qaytaradi." },
      { key: "history", title: "To'liq tarix", desc: "Kim qachon nima qilgani tarixda saqlanib qoladi." },
    ],
    footer: "Barcha huquqlar himoyalangan.",
  },
} as const;
