/**
 * Barcha interfeys matnlari — BITTA joyda (CLAUDE.md, 8-bo'lim).
 * Auditoriya 18–40 yosh: qisqa, oddiy, texnik atamasiz so'zlar.
 */
export const T = {
  app: "TeamFlow",
  common: {
    save: "Saqlash",
    cancel: "Bekor qilish",
    close: "Yopish",
    back: "Orqaga",
    next: "Keyingi",
    edit: "Tahrirlash",
    delete: "O'chirish",
    add: "Qo'shish",
    open: "Ochish",
    download: "Yuklab olish",
    search: "Qidirish",
    pages: "Sahifalar",
    clear: "Tozalash",
    all: "Hammasi",
    loading: "Yuklanmoqda…",
    retry: "Qayta urinish",
    none: "—",
    notSet: "Belgilanmagan",
    confirmDelete: "Rostdan o'chirilsinmi? Bu amalni qaytarib bo'lmaydi.",
    yes: "Ha, o'chirish",
    unsaved: "Saqlanmagan o'zgarishlar bor. Baribir yopilsinmi?",
    errorGeneric: "Nimadir xato ketdi. Internetni tekshirib, qayta urinib ko'ring.",
    forbidden: "Bu amal uchun ruxsatingiz yo'q.",
    notFound: "Topilmadi yoki sizga ko'rinmaydi.",
    saved: "Saqlandi",
    files: "Fayllar",
    noFiles: "Fayl yo'q",
    attach: "Fayl biriktirish",
    attachHint: "Word, PDF yoki rasm · 20 MB gacha",
    comments: "Izohlar",
    required: "Majburiy maydon",
    daysLeft: (n: number) => (n === 0 ? "Bugun tugaydi" : `${n} kun qoldi`),
    daysLate: (n: number) => `${n} kun kechikdi`,
    count: (n: number) => `${n} ta`,
  },
  time: {
    now: "hozirgina",
    minutes: (n: number) => `${n} daqiqa oldin`,
    hours: (n: number) => `${n} soat oldin`,
    days: (n: number) => `${n} kun oldin`,
  },
  taskStatusHint: {
    control: "Topshiriq berildi, hali boshlanmagan",
    in_progress: "Ustida ishlanmoqda",
    in_review: "Menejer tekshirmoqda",
    done: "Qabul qilindi",
  } as Record<string, string>,

  nav: {
    groupMain: "Asosiy ish",
    groupTeam: "Muloqot",
    groupControl: "Kuzatuv",
    dashboard: "Bosh panel",
    projects: "Loyihalar",
    orders: "Buyurtmalar (TZ)",
    myOrders: "Buyurtmalarim",
    tasks: "Topshiriqlar",
    myWork: "Mening ishim",
    calendar: "Taqvim",
    people: "Xodimlar",
    notifications: "Bildirishnomalar",
    suggestions: "Takliflar",
    review: "Tekshiruv navbati",
    logout: "Chiqish",
    menu: "Menyu",
    theme: "Tungi / kunduzgi rejim",
    searchPlaceholder: "Topshiriq, loyiha yoki odamni qidiring",
    profile: "Profil",
    workDone: "Qilingan ishlar",
    messages: "Xabarlar",
  },

  auth: {
    loginTitle: "Tizimga kirish",
    loginSubtitle: "Jamoa ishini bir joyda kuzating",
    username: "Login",
    password: "Parol",
    login: "Kirish",
    noAccount: "Akkauntingiz yo'qmi?",
    register: "Ro'yxatdan o'tish",
    registerTitle: "Ro'yxatdan o'tish",
    registerSubtitle: "Ma'lumotlaringizni to'ldiring — administrator tasdiqlagach kirasiz",
    firstName: "Ism",
    lastName: "Familiya",
    specialty: "Mutaxassislik",
    specialtyPick: "Tanlang",
    role: "Rolingiz",
    departmentName: "Boshqarma nomi",
    departmentHint: "Masalan: Axborot texnologiyalari boshqarmasi",
    passwordHint: "Kamida 8 belgi, faqat raqamdan iborat bo'lmasin",
    telegram: "Telegram (ixtiyoriy)",
    telegramHint: "Bildirishnomalar uchun, masalan: @username",
    telegramPh: "@username",
    haveAccount: "Akkauntingiz bormi?",
    registered: "Arizangiz yuborildi!",
    registeredText: "Administrator akkauntingizni tasdiqlagach, login va parolingiz bilan kira olasiz.",
    toLogin: "Kirish sahifasiga",
    roleHints: {
      pm: "Loyiha yaratadi, topshiriq beradi, ishni tekshiradi",
      developer: "Topshiriqlarni bajaradi",
      department: "Buyurtma (TZ) yuboradi",
    } as Record<string, string>,
  },

  dashboard: {
    hello: (name: string) => `Salom, ${name}!`,
    managerSummary: (review: number, orders: number) =>
      review || orders
        ? `Sizni kutmoqda: ${review} ta tekshiruv, ${orders} ta yangi buyurtma.`
        : "Hozircha sizni kutayotgan ish yo'q.",
    devSummary: (active: number, overdue: number) =>
      active
        ? `Sizda ${active} ta faol topshiriq${overdue ? `, ${overdue} tasining muddati o'tgan` : ""}.`
        : "Faol topshirig'ingiz yo'q. Dam oling yoki menejeringizga yozing.",
    weeklyHeroTitle: "Haftalik jami ishlar",
    weeklyHeroSubtitle: (since: string) => `${since} dan bugungacha bo'lgan jami haftalik topshiriqlar`,
    weeklyTotal: (n: number) => `Jami: ${n} ta`,
    weekActive: "Hafta boshidan — Faol",
    team: "Jamoa",
    teamHint: "Topshirig'i yo'qlar birinchi turadi",
    everyone: "Hamma xodimlar",
    free: "Bo'sh",
    active: "Faol",
    overdue: "Muddati o'tgan",
    done: "Bajarilgan",
    late: "Kechikib bajarilgan",
    review: "Tekshiruv kutilmoqda",
    since: (d: string) => `${d} — bugun`,
    doingNow: "Hozir ustida ishlayapti",
    noDoing: "Hozir jarayonda topshiriq yo'q",
    personTasks: "Topshiriqlari",
    tableTitle: (a: string, b: string) => `${a} — ${b}`,
    pickCard: "Ro'yxatni ko'rish uchun istalgan raqamni bosing",
    departmentTitle: "Buyurtmalaringiz holati",
    deptOrders: "Buyurtmalaringiz",
    deptSent: "Yuborilgan",
    deptRejected: "Rad etilgan",
    deptApproved: "Tasdiqlangan",
  },

  filters: {
    search: "Qidiruv",
    searchPh: "Topshiriq nomi",
    due: "Muddat",
    dueAll: "Hammasi",
    dueToday: "Bugun",
    dueWeek: "Shu hafta",
    dueMonth: "Shu oy",
    date: "Sana",
    dateRange: "Sana (dan — gacha)",
    dateFrom: "Sanadan",
    dateTo: "Sanagacha",
    status: "Holat",
    project: "Loyiha",
    person: "Xodim",
    personPh: "Xodim ismi",
    allProjects: "Barcha loyihalar",
    toggle: "Filtrlar",
    clear: "Filtrni tozalash",
  },

  tasks: {
    title: "Topshiriqlar",
    new: "Yangi topshiriq",
    empty: "Topshiriq topilmadi",
    emptyHint: "Filtrlarni tozalab ko'ring yoki yangi topshiriq yarating.",
    col: { title: "Topshiriq", status: "Holat", priority: "Muhimlik", assignees: "Ijrochilar", due: "Muddat" },
    project: "Loyiha",
    name: "Topshiriq nomi",
    namePh: "Masalan: Kirish sahifasini yaratish",
    description: "Izoh",
    descriptionPh: "Nima qilish kerakligini qisqacha yozing",
    priority: "Muhimlik",
    startsAt: "Boshlanish vaqti",
    dueAt: "Tugash vaqti (muddat)",
    assignees: "Ijrochilar",
    assigneesHint: "Bir nechta dasturchini tanlash mumkin. Faqat loyiha jamoasi ko'rinadi.",
    noTeam: "Loyihada hali dasturchi yo'q. Avval loyihaga jamoa qo'shing.",
    pickProject: "Avval loyihani tanlang",
    subtasks: "Sub-vazifalar",
    subtaskPh: "Kichik qadam",
    subtaskAdd: "Sub-vazifa qo'shish",
    subtaskNobody: "Hamma",
    createdBy: "Topshiriqni bergan",
    tabMain: "Umumiy",
    tabReview: "Tekshiruv tarixi",
    start: "Boshlash",
    submit: "Tekshiruvga yuborish",
    submitTitle: "Nima qildingiz?",
    submitPh: "Qilgan ishingizni qisqacha yozing — menejer shuni ko'radi",
    submitSend: "Yuborish",
    accept: "Qabul qilish",
    return: "Qaytarish",
    returnTitle: "Nima tuzatilishi kerak?",
    returnPh: "Dasturchi nimani tuzatishini aniq yozing",
    returnSend: "Qaytarish",
    round: (n: number) => `${n}-urinish`,
    noSubmissions: "Hali tekshiruvga yuborilmagan",
    reviewer: "Tekshirdi",
    createdToast: "Topshiriq yaratildi",
    startedToast: "Topshiriq boshlandi",
    submittedToast: "Tekshiruvga yuborildi",
    submitAckRequestedToast: "Ijrochidan so'ralgan tasdiqdan keyin tekshiruvga yuboriladi",
    submitAckPending: (names: string) => `Tekshiruvga yuborishdan oldin ijrochi tasdig'i kutilmoqda: ${names}`,
    acceptedToast: "Topshiriq qabul qilindi",
    returnedToast: "Topshiriq qaytarildi",
    deletedToast: "Topshiriq arxivlandi",
    archiveConfirm: "Topshiriq ro'yxatdan olinadi. Ish tarixi va fayllari saqlanadi.",
    archived: "Arxivlangan",
    info: "Ma'lumotlar",
    createdByShort: "Yaratdi",
    noFiles: "Fayllar yo'q",
    worklog: (hours: number) => `Ish jurnali (${hours} soat)`,
    worklogHours: "Sarflangan soat",
    worklogPh: "Bugun nima qildingiz?",
    worklogSave: "Qayd etish",
    worklogEmpty: "Hali ish qayd etilmagan. Qilgan ishingizni va sarflangan vaqtni yozib boring.",
    worklogItem: (hours: number) => `${hours} soat`,
    worklogSavedToast: "Ish jurnali saqlandi",
    subtaskAddedToast: "Sub-vazifa qo'shildi",
    subtaskDeletedToast: "Sub-vazifa o'chirildi",
    subtaskNewPh: "Nima qilinishi kerak?",
    subtaskPickPerson: "Kimga (ixtiyoriy)",
    subtaskPeople: "Ijrochilar",
    subtaskPeopleSavedToast: "Sub-vazifa ijrochilari saqlandi",
    picker: {
      searchPh: "Dasturchi ismini yozing",
      add: "Qo'shish",
      remove: (name: string) => `${name}ni olib tashlash`,
      noMatch: "Bunday dasturchi topilmadi",
      joinHint: "Jamoada bo'lmagan dasturchi tanlansa, u loyiha jamoasiga ham qo'shiladi.",
    },
    assigneesEdit: "O'zgartirish",
    assigneesSavedToast: "Ijrochilar saqlandi",
    upload: "Yuklash",
    bulkNew: "Ko'p topshiriq qo'shish",
    bulkTitle: "Topshiriqlarni taqsimlash",
    bulkSubtitle: "Har bir topshiriqqa ijrochi tanlang",
    bulkMore: "Yana topshiriq",
    notInTeam: "Tanlangan xodim bu loyiha jamoasida emas.",
    addToTeam: "Jamoaga qo'shish",
    addedToTeamToast: "Xodim loyiha jamoasiga qo'shildi",
  },

  board: {
    title: "Mening ishim",
    hint: "Kartani sichqoncha bilan keyingi ustunga sudrang",
    emptyCol: "Bu yerga karta sudrang",
    emptyDone: "Menejer qabul qilgan topshiriqlar shu yerda",
    locked: "Faqat menejer qabul qiladi",
    cantMove: "Topshiriqni bu ustunga o'tkazib bo'lmaydi",
    moveTo: "O'tkazish",
    actions: "Amallar",
  },

  review: {
    title: "Tekshiruv navbati",
    empty: "Tekshiruvni kutayotgan topshiriq yo'q",
    emptyHint: "Dasturchi ishni yuborganda shu yerda paydo bo'ladi.",
    sentBy: "Yubordi",
    open: "Ko'rib chiqish",
  },

  orders: {
    title: "Buyurtmalar (TZ)",
    myTitle: "Buyurtmalarim",
    new: "Yangi buyurtma",
    empty: "Buyurtma yo'q",
    emptyDept: "Birinchi buyurtmangizni yuboring — TZ faylini biriktiring va muddatni belgilang.",
    emptyManager: "Boshqarmalar buyurtma yuborganda shu yerda ko'rinadi.",
    tabs: { submitted: "Yangi", approved: "Tasdiqlangan", rejected: "Rad etilgan" } as Record<string, string>,
    name: "Buyurtma nomi",
    namePh: "Masalan: Hujjat aylanishi tizimi",
    description: "Qisqacha izoh",
    descriptionPh: "Nima kerakligini 2–3 gapda yozing",
    priority: "Muhimlik",
    dueDate: "Qachongacha kerak",
    tzFile: "TZ fayli",
    tzHint: "Word (.docx) yoki PDF",
    send: "Yuborish",
    sentToast: "Buyurtma yuborildi",
    department: "Boshqarma",
    sender: "Yuborgan",
    requestedDue: "So'ralgan muddat",
    pmDates: "Menejer belgilagan muddat",
    responsiblePm: "Mas'ul menejer",
    sentAt: "Yuborilgan",
    pmNote: "Menejer izohi",
    steps: ["Yuborildi", "Ko'rib chiqish", "Qaror", "Loyiha"],
    tabMain: "Umumiy",
    tabDoc: "TZ hujjat",
    tabHistory: "Versiyalar",
    version: (n: number) => `v${n}`,
    fixed: "Nima tuzatildi",
    rejectReason: "Rad etish sababi",
    approve: "Tasdiqlash",
    approveTitle: "Muddatni belgilang",
    startDate: "Boshlanish sanasi",
    endDate: "Tugash sanasi",
    note: "Qisqa izoh",
    notePh: "Boshqarmaga izoh (ixtiyoriy)",
    reject: "Rad etish",
    rejectTitle: "Nima uchun rad etilyapti?",
    rejectPh: "Boshqarma nimani tuzatishi kerakligini yozing",
    newVersion: "Yangi TZ yuborish",
    newVersionTitle: "Tuzatilgan TZ",
    newVersionPh: "Qaysi kamchiliklar tuzatildi?",
    waitingDecision: "TZ ko'rib chiqilmoqda. Qaror chiqquncha yangi versiya yuborib bo'lmaydi.",
    rejectedInfo: "Buyurtma rad etildi. Kamchiliklarni tuzatib, yangi TZ yuboring.",
    createProject: "Loyiha yaratish",
    openProject: "Loyihani ochish",
    editDates: "Sanani o'zgartirish",
    approvedToast: "Buyurtma tasdiqlandi",
    rejectedToast: "Buyurtma rad etildi",
    versionToast: "Yangi TZ yuborildi",
    datesToast: "Sanalar yangilandi",
    completionTitle: "Loyiha yakunlandi deb belgilandi",
    confirmCompletion: "Yakunlashni tasdiqlash",
    rejectCompletion: "Kamchilik bor",
    rejectCompletionTitle: "Nima kamchilik bor?",
    rejectCompletionPh: "Loyiha menejeri nimani tuzatishi kerakligini yozing",
    completionConfirmedToast: "Loyiha yakunlanishi tasdiqlandi",
    completionRejectedToast: "Loyiha menejerga qaytarildi",
  },

  projects: {
    title: "Loyihalar",
    new: "Yangi loyiha",
    empty: "Loyiha yo'q",
    emptyHint: "Loyiha yarating yoki tasdiqlangan buyurtmadan loyiha oching.",
    emptyDev: "Sizni hali loyihaga qo'shishmagan.",
    code: "Loyiha raqami",
    codePh: "Masalan: PRJ-12",
    codeHint: "Boshqa loyihada ishlatilmagan bo'lishi kerak.",
    name: "Loyiha nomi",
    namePh: "Masalan: Ichki portal",
    description: "Izoh",
    stage: "Holati",
    startDate: "Boshlanish",
    endDate: "Tugash",
    team: "Jamoa",
    teamHint: "Loyihada ishlaydigan dasturchilarni belgilang",
    teamEmpty: "Hali dasturchi qo'shilmagan",
    progress: (d: number, t: number) => `${d} / ${t} topshiriq bajarildi`,
    fromOrder: "Buyurtmadan",
    fromOrderLocked: "Buyurtmadan yaratilgan: bu yerdagi o'zgarish bog'liq buyurtmaga ham ko'chadi.",
    pendingApproval: "Loyiha yakunlandi deb belgilandi — endi buyurtma beruvchi boshqarma tasdiqlashini kutmoqda.",
    requestCompletion: "Yakunlash",
    requestCompletionToast: "Boshqarmaga yuborildi, tasdiqlashini kuting",
    completionAckToast: "Dasturchilarga so'rov yuborildi, javobini kutamiz",
    completionAckPending: (names: string) => `Yakunlashdan oldin dasturchi tasdig'i kutilmoqda: ${names}`,
    completionAckConfirmed: (names: string) => `Tasdiqladi: ${names}`,
    steps: ["Asosiy", "Jamoa", "Topshiriq va fayllar"],
    projectFiles: "Loyiha fayllari",
    memberTasks: "Xodimlarga topshiriqlar (ixtiyoriy)",
    memberTasksHint: "Har bir xodimga alohida topshiriq bering: nomi, boshlanish va tugash vaqti, kerak bo'lsa fayl.",
    memberNoTasks: "Hali topshiriq berilmagan",
    quickTaskPh: "Topshiriq nomi",
    quickTaskAdd: "Topshiriq qo'shish",
    taskFiles: "Topshiriqqa fayl biriktirish",
    taskEndBeforeStart: "Tugash vaqti boshlanishdan oldin bo'lmasin",
    create: "Loyihani yaratish",
    createdToast: "Loyiha yaratildi",
    tabMain: "Umumiy",
    tabTasks: "Topshiriqlar",
    tabTeam: "Jamoa",
    tabFiles: "Fayllar",
    addTask: "Topshiriq qo'shish",
    saveTeam: "Jamoani saqlash",
    teamSaved: "Jamoa yangilandi",
    teamSearchPh: "Dasturchini qidiring va qo'shing",
    teamAdd: "Qo'shish",
    teamRemove: "Olib tashlash",
    teamNoMatch: "Bunday dasturchi topilmadi",
    teamUnsaved: "Saqlanmagan",
    teamSaveFirst: "Topshiriq berishdan oldin jamoani saqlang.",
    giveTask: "Topshiriq berish",
    order: "Buyurtma",
    createdBy: "Yaratgan",
    endBeforeStart: "Tugash sanasi boshlanishdan oldin bo'lmasin",
    tzIncluded: (name: string) => `Buyurtma TZ fayli avtomatik qo'shiladi: ${name}`,
    noActivity: "Hali faoliyat yo'q.",
    tabHistory: "Tarix",
    activityTitle: "Loyiha faolligi",
  },

  calendar: {
    title: "Taqvim",
    today: "Bugun",
    weekdays: ["Du", "Se", "Ch", "Pa", "Ju", "Sh", "Ya"],
    months: ["Yanvar", "Fevral", "Mart", "Aprel", "May", "Iyun", "Iyul", "Avgust", "Sentyabr", "Oktyabr", "Noyabr", "Dekabr"],
    more: (n: number) => `yana ${n} ta`,
    hint: "Topshiriqlar va loyihalar tugash sanasi bo'yicha. Kunni bosing — o'sha kun ro'yxati ochiladi",
    openDay: (date: string) => `${date} — kun ro'yxatini ochish`,
    projectEnds: (name: string) => `${name} — loyiha tugaydi`,
    dayProjects: "Shu kuni tugaydigan loyihalar",
    dayTasks: "Shu kungi topshiriqlar",
    dayCount: (tasks: number, projects: number) =>
      [tasks && `${tasks} ta topshiriq`, projects && `${projects} ta loyiha`].filter(Boolean).join(" · ") || "Hech narsa yo'q",
    dayEmpty: "Bu kunga topshiriq ham, loyiha muddati ham yo'q",
    dayEmptyHint: "Boshqa kunni tanlang yoki taqvimni oylar bo'yicha aylantiring.",
  },

  notifications: {
    title: "Bildirishnomalar",
    readAll: "Hammasini o'qildi deb belgilash",
    empty: "Bildirishnoma yo'q",
    emptyHint: "Yangi topshiriq, tekshiruv yoki buyurtma bo'lsa, shu yerda ko'rasiz.",
    unread: "O'qilmagan",
    unreadCount: (n: number) => `${n} ta o'qilmagan bildirishnoma`,
    allRead: "Hammasi o'qilgan",
    emptyUnread: "O'qilmagan bildirishnoma yo'q",
    emptyUnreadHint: "Hammasini ko'rib chiqdingiz. Yangisi kelsa, shu yerda paydo bo'ladi.",
    today: "Bugun",
    yesterday: "Kecha",
    ackConfirm: "Ha, tayyor",
    ackReject: "Yo'q",
    ackReasonPh: "Sababini yozing…",
    ackReasonSend: "Yuborish",
    ackReasonRequired: "Sababini yozing",
    ackSent: "Javobingiz yuborildi",
  },

  comments: {
    empty: "Hali izoh yo'q. Birinchi bo'lib yozing.",
    placeholder: "Izoh yozing…",
    send: "Yuborish",
  },

  docs: {
    loading: "Hujjat ochilmoqda…",
    failed: "Hujjatni ko'rsatib bo'lmadi. Yuklab olib oching.",
    unsupported: "Bu turdagi faylni oldindan ko'rib bo'lmaydi. Yuklab oling.",
    zoomIn: "Kattalashtirish",
    zoomOut: "Kichraytirish",
    fullscreen: "To'liq ekran",
  },

  search: {
    title: "Qidiruv",
    placeholder: "Topshiriq, loyiha, odam, topshiriq kodi yoki loyiha raqami…",
    min: "Kamida 2 ta harf yozing",
    empty: "Hech narsa topilmadi",
    groups: { tasks: "Topshiriqlar", projects: "Loyihalar", orders: "Buyurtmalar", people: "Odamlar" } as Record<string, string>,
  },

  profile: {
    title: "Profil",
    businessTrips: "Xizmat safarlari",
    businessTripHint: "Boshliq xodimning qaytish sanasini belgilaydi. Shu sanagacha unga yangi topshiriq berilmaydi.",
    tripEmployee: "Xodim",
    tripReturnDate: "Qaytish sanasi",
    tripSet: "Xizmat safariga chiqarish",
    tripEnd: "Safarni muddatidan oldin tugatish",
    tripSaved: "Xizmat safari saqlandi",
    tripEnded: "Xizmat safari tugatildi",
    photoUpload: "Rasm yuklash",
    photoChange: "Rasmni almashtirish",
    photoRemove: "Rasmni o'chirish",
    photoHint: "JPG, PNG yoki WEBP, 5 MB gacha",
    photoSavedToast: "Rasm saqlandi",
    photoRemovedToast: "Rasm o'chirildi",
    passwordTitle: "Parolni almashtirish",
    currentPassword: "Joriy parol",
    newPassword: "Yangi parol",
    changePassword: "Parolni almashtirish",
    passwordChangedToast: "Parol muvaffaqiyatli o'zgartirildi",
    editInfoTitle: "Ma'lumotlarni tahrirlash",
    firstName: "Ism",
    lastName: "Familiya",
    dateJoined: "Tizimga qo'shilgan vaqt",
    telegram: "Telegram",
    telegramHint: "Bildirishnomalar Telegram'ga ham kelsin desangiz: username yozing va botga /start yuboring.",
    /** Bot havolasi bilan: "…username yozing, saqlang va [@bot] ga /start yuboring." */
    telegramHintBefore: "Bildirishnomalar Telegram'ga ham kelsin desangiz: username yozing, saqlang va",
    telegramHintAfter: "botiga /start yuboring.",
    telegramPh: "@username",
    login: "Login",
    stats: "Topshiriqlaringiz",
    myTasks: "Mening topshiriqlarim",
    myTasksEmpty: "Sizga hali topshiriq berilmagan. Menejer topshiriq berganda shu yerda ko'rasiz.",
    savedToast: "Ma'lumotlar saqlandi",
  },

  people: {
    onBusinessTrip: "Xizmat safarida",
    tripUntil: (date: string) => `Qaytish sanasi: ${date}`,
    tripBlocked: "Xizmat safaridan qaytguncha yangi topshiriq berib bo'lmaydi",
    photoOpen: "Rasmni kattalashtirish",
    photoOf: (name: string) => `${name} — profil rasmi`,
    profileTitle: "Xodim profili",
    noTasksHint: "Bu xodimga hali topshiriq berilmagan. \"Topshiriq berish\" tugmasi orqali bering.",
    onlyFree: "Bo'sh xodimlar",
    viewTable: "Jadval",
    viewGrid: "Kartalar",
    searchPh: "Xodimni qidirish…",
    empty: "Xodimlar topilmadi",
    emptyHint: "Qidiruv yoki filtrni o'zgartirib ko'ring.",
    col: { person: "Xodim", position: "Lavozim / Bo'lim", load: "Bandlik", tasks: "Topshiriqlar", doing: "Hozir nima qilyapti", actions: "Amallar" },
    activeN: (n: number) => `${n} faol`,
    overdueN: (n: number) => `${n} kechikkan`,
    reviewN: (n: number) => `${n} tekshiruvda`,
    doneN: (n: number) => `${n} bajarilgan`,
    noTasks: "Topshiriq yo'q",
    giveTask: "Topshiriq berish",
    freeNow: "Hozir bo'sh — topshirig'i yo'q",
    busyNow: (n: number) => `Band: ${n} ta faol topshiriq`,
    freeHint: "Xodimga yangi topshiriq bering",
    busyHint: "Yana topshiriq berish mumkin",
    tasks: "Topshiriqlar",
    report: "Dasturchi hisoboti",
    donePercent: "Bajarilish foizi",
    onTimeRate: "O'z vaqtida bajarganlar ulushi",
    total: "Jami topshiriqlar:",
    doneTotal: "Bajarilgan:",
    doneLate: "Kechikib bajarilgan:",
    lateNow: "Hozir kechikkan:",
    reportNote: "Hisobot barcha topshiriqlar asosida. \"O'z vaqtida\" — bajarilganlardan qanchasi muddatidan oldin yopilgani.",
    devOnly: "Batafsil hisobot faqat dasturchilar uchun.",
  },

  chat: {
    searchPh: "Ism bo'yicha qidirish",
    notFound: "Hech kim topilmadi",
    noConversations: "Hali suhbat yo'q",
    noConversationsHint: "Yuqoridagi qidiruvdan hamkasbingizni toping va yozing.",
    pickTitle: "Suhbatni tanlang",
    pickHint: "Chapdagi ro'yxatdan suhbatni oching yoki qidiruv orqali yangi odamga yozing.",
    firstMessage: "Hali xabar yo'q. Birinchi bo'lib yozing!",
    messagePh: "Xabar yozing…",
    send: "Yuborish",
  },

  workDone: {
    title: "Qilingan ishlar",
    tabs: { tasks: "Topshiriqlar", reviews: "Tekshiruvlar", history: "Tarix" } as Record<string, string>,
    mine: "Faqat men",
    days: "Kun",
    noTasks: "Yaqin orada bajarilgan topshiriqlar yo'q.",
    noReviews: "Yaqin orada tekshiruvlar yo'q.",
    noHistory: "Yaqin orada tarix yo'q.",
    decision: "Qaror",
    col: {
      task: "Topshiriq", project: "Loyiha", assignees: "Ijrochilar", doneAt: "Bajarildi",
      submittedBy: "Yubordi", note: "Izoh", reviewer: "Tekshirdi", date: "Sana",
      person: "Xodim", action: "Nima qildi", time: "Vaqt",
    },
    prev: "← Oldingi",
    next: "Keyingi →",
    page: (n: number) => `${n}-sahifa`,
  },

  suggestions: {
    title: "Takliflar",
    new: "Yangi taklif",
    empty: "Takliflar yo'q",
    emptyHint: "O'z taklifingizni yozib qoldiring.",
    name: "Sarlavha",
    namePh: "Qisqacha nima haqida",
    body: "Taklif matni",
    bodyPh: "Batafsil tushuntirib bering",
    anonymous: "Anonim yuborish (ismingiz ko'rinmaydi)",
    author: "Muallif",
    anonymousAuthor: "Anonim",
    status: "Holat",
    tabs: { pending: "Ko'rib chiqilmoqda", accepted: "Qabul qilingan", rejected: "Rad etilgan" } as Record<string, string>,
    votes: "Ovozlar",
    voteFor: "Yoqlayman",
    voteAgainst: "Qarshiman",
    removeVote: "Ovozni bekor qilish",
    bossDecision: "Boshliq qarori",
    bossNote: "Boshliq izohi",
    accept: "Qabul qilish",
    reject: "Rad etish",
    sentToast: "Taklif yuborildi",
    votedToast: "Ovoz berildi",
    decidedToast: "Qaror qabul qilindi",
    deletedToast: "Taklif o'chirildi",
    send: "Yuborish",
    voteCounts: (forN: number, againstN: number) => `${forN} yoqlaydi · ${againstN} qarshi`,
    bossNotePh: "Qaroringiz sababini qisqacha yozing (ixtiyoriy)",
  },
  landing: {
    title: "Jamoangiz bir joyda ishlaydigan platforma",
    subtitle: "Loyiha oching, jamoani mutaxassisligi bo'yicha yig'ing, topshiriqlarni bering va hammasini bitta tizimda kuzatib boring.",
    register: "Ro'yxatdan o'tish",
    login: "Kirish",
    features: [
      { key: "board", title: "Topshiriqlar doskasi", desc: "Topshiriqni ustunlar bo'ylab sudrab o'tkazing — kim nima qilayotgani darrov ko'rinadi." },
      { key: "orders", title: "Boshqarmalar bilan ishlash", desc: "Buyurtmalarni qabul qiling va ularni loyihaga aylantiring." },
      { key: "review", title: "Ishni tekshirish", desc: "Bajarilgan topshiriq menejerga tekshiruvga tushadi, u qabul qiladi yoki qaytaradi." },
      { key: "history", title: "To'liq tarix", desc: "Kim qachon nima qilgani tarixda saqlanib qoladi." },
    ],
    footer: "Barcha huquqlar himoyalangan.",
  },
} as const;
