# Generated by Django 5.2.17 on 2026-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Bildirishnomalar uchun, ms: @username', max_length=100, verbose_name='Telegram'),
        ),
    ]
