# Generated by Django 5.2.17 on 2026-09-30 12:13

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.core.files.UploadTo('avatars'), verbose_name='Rasm'),
        ),
    ]
