# Generated by Django 5.2.17 on 2026-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_business_trip_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='responsibilities',
            field=models.TextField(blank=True, max_length=2000, verbose_name="Mas'uliyatlar"),
        ),
    ]
