# Generated by Django 5.2.17 on 2026-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_responsibilities'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role', 'first_name', 'last_name'], name='user_active_role_name_idx'),
        ),
    ]
