# Generated by Django 5.2.17 on 2026-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_user_active_role_name_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('boss', 'Boshliq'), ('pm', 'Loyiha menejeri'), ('developer', 'Dasturchi'), ('department', 'Boshqarma'), ('user', 'Oddiy foydalanuvchi')], max_length=16, verbose_name='Rol'),
        ),
    ]
