# Generated by Django 5.2.17 on 2026-09-28 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Ish sanasi')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Sarflangan soat')),
                ('note', models.TextField(verbose_name='Bajarilgan ish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='tasks.task')),
            ],
            options={
                'ordering': ['-work_date', '-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hours__gt', 0), ('hours__lte', 24)), name='worklog_hours_range')],
            },
        ),
    ]
