# Generated by Django 5.2.17 on 2026-10-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_subtask_assignees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Topshiriq', 'verbose_name_plural': 'Topshiriqlar'},
        ),
    ]
