# Generated by Django 5.2.17 on 2026-10-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_subtask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.CharField(editable=False, max_length=9, null=True, unique=True, verbose_name='Kod'),
        ),
    ]
