# Generated by Django 5.2.17 on 2026-10-06 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_completion_note_projectfile_is_completion'),
        ('tasks', '0008_task_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['archived_at', 'status', 'due_at'], name='task_active_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'archived_at', 'due_at'], name='task_project_active_due_idx'),
        ),
    ]
