# Generated by Django 5.2.17 on 2026-10-05 11:01

import apps.core.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pending_submit_note',
            field=models.TextField(blank=True, verbose_name='Kutilayotgan izoh'),
        ),
        migrations.AddField(
            model_name='task',
            name='submit_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Tekshiruvga yuborish tasdig'i so'ralgan payt"),
        ),
        migrations.AddField(
            model_name='task',
            name='submit_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="Tekshiruvga yuborishni so'ragan menejer"),
        ),
        migrations.CreateModel(
            name='TaskSubmitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.core.files.UploadTo('tasks/submit_attachments'), validators=[apps.core.files.validate_upload])),
                ('original_name', models.CharField(max_length=255, verbose_name='Asl fayl nomi')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_attachments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Kutilayotgan tekshiruv fayli',
                'verbose_name_plural': 'Kutilayotgan tekshiruv fayllari',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmitAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=None, null=True, verbose_name='Tasdiqladi')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Rad etish sababi')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_acks', to='tasks.task')),
            ],
            options={
                'verbose_name': "Tekshiruvga yuborish tasdig'i",
                'verbose_name_plural': 'Tekshiruvga yuborish tasdiqlari',
                'constraints': [models.UniqueConstraint(fields=('task', 'developer'), name='uniq_task_submit_ack')],
            },
        ),
    ]
