# Generated by Django 5.2.17 on 2026-10-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_pending_submit_note_task_submit_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Sub-vazifa', 'verbose_name_plural': 'Sub-vazifalar'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Topshiriq', 'verbose_name_plural': 'Topshiriqlar'},
        ),
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'verbose_name': 'Topshiriq ijrochisi', 'verbose_name_plural': 'Topshiriq ijrochilari'},
        ),
        migrations.AlterModelOptions(
            name='taskfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Topshiriq fayli', 'verbose_name_plural': 'Topshiriq fayllari'},
        ),
    ]
