# Generated by Django 5.2.17 on 2026-10-06 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_task_active_status_due_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['developer', 'task'], name='assignment_developer_task_idx'),
        ),
    ]
