# Generated by Django 5.2.17 on 2026-10-06 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_project_end_stage_idx'),
        ('tasks', '0010_taskassignment_assignment_developer_task_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['archived_at', 'due_at', '-created_at', '-id'], name='task_active_due_order_idx'),
        ),
    ]
