# Generated by Django 5.2.17 on 2026-09-28 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['recipient', 'author', '-created_at'], name='chat_recipient_partner_idx'),
        ),
    ]
