# Generated by Django 5.2.17 on 2026-10-06 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_chat_recipient_partner_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['author', 'recipient', '-id'], name='chat_partner_cursor_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['recipient', 'is_read', 'author'], name='chat_unread_author_idx'),
        ),
    ]
